### ISSUE TITLE
Strange formatting

### ISSUE THREAD

**Issue by jonsag** [JulianGmp/vscode-openscad-formatter#3]
Sorry for bringing this up after all the work, but it's still formatting in an unwanted way.
Code is valid, but doesn't look good.

Try formatting this:
```
// base.scad

include <config.scad>

use <joystick.scad>
use <board.scad>
use <encoder.scad>

// calculations
module baseShell() {
    cylinder(h = baseHeight, d = baseDia, center = true, $fn = roundness);
}
```

Formats with a whole lot of unwanted tab inserts for me:
```
// base.scad

include <config.scad>

use <joystick.scad>
use <board.scad>
use <encoder.scad>

                // calculations
                module baseShell()
{
	cylinder(h = baseHeight, d = baseDia, center = true, $fn = roundness);
}
```

The number of tabs inserted seems to depend on how many 'include' and 'use' there is.

Thanks for your work!
/jon

**Comment by jonsag** [comment]
After more investigating it seems the include directive has no impact on this, only use.

**Comment by JulianGmp** [comment]
I looked into it, I was merely wrapping the include and use statements between a `clang-format off` and `clang-format on`, which would make clang-format leave the lines alone, but they're still taken into account for indentation.

The "fix" I just released also wraps the statements into comments, so clang-format will see something like this:

```scad
// JulianGmp.openscad-formatter begin
// clang-format off
/*
use <somefile.scad>
*/
// clang-format on'
// JulianGmp.openscad-formatter end'
```

This extension gets hackier and hackier but it works™

**Comment by jonsag** [comment]
As long as it works I'm completely happy with it. :-)

Thanks for all your work!
